### ISSUE TITLE
False positive.

### ISSUE THREAD

**Issue by dmitshur** [alexkohler/unimport#1]
In your [README](https://github.com/alexkohler/unimport#example), one of the examples is:

```
go/build/build.go:19 unnecessary import alias pathpkg
```

That appears to be a false positive. That import rename of path package is neccessary. Without it, the `Context.Import` method would have a name conflict:

```Go
func (ctxt *Context) Import(path string, srcDir string, mode ImportMode) (*Package, error) {
	p := &Package{
		ImportPath: path,
	}
	if path == "" {
		return p, fmt.Errorf("import %q: invalid import path", path)
	}
...
	setPkga := func() {
		switch ctxt.Compiler {
		case "gccgo":
			dir, elem := pathpkg.Split(p.ImportPath) // if this were path.Split, that wouldn't compile because path is a string here
...
```

**Comment by alexkohler** [comment]
Nice catch! The package alias is probably less impactful to consumers of the API than renaming the `path` variable. Will update :)
